name: CI Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t test-sienatest . -f Dockerfile.test
      - name: Run integration tests
        run: docker run --rm test-sienatest
